// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/itfeeds/internal/dao/internal"
)

// rssEntriesDao is the data access object for the table rss_entries.
// You can define custom methods on it to extend its functionality as needed.
type rssEntriesDao struct {
	*internal.RssEntriesDao
}

var (
	// RssEntries is a globally accessible object for table rss_entries operations.
	RssEntries = rssEntriesDao{internal.NewRssEntriesDao()}
)

// Add your custom methods and functionality below.
